### PR TITLE
Added check for sudo

### PR DESCRIPTION
**Pull request by jaevibing**
Added a check to see if the user is running the script as sudo.

### CODE REVIEW

**Comment by Sanchiters** [comment]
Can't find the link for the discord server please help.

**Comment by jaevibing** [comment]
> Can't find the link for the discord server please help.

This is a pull request, you won't get any help with the Discord here.

**Comment by RRR06** [comment]
> Can't find the link for the discord server please help.

https://discord.gg/hd3K8PH Checkout the discord server at that link

**Comment by RRR06** [comment]
> > Can't find the link for the discord server please help.
> 
> This is a pull request, you won't get any help with the Discord here.

I am archiving this repo, the solutions are now more oriented to workarounds involving less code. Besides my capabilities as a software engineer have drastically improved ever since I created this repo, so they would be much more fancy rather than just simple shell scripts. But I do appreciate your efforts

**Pull request closed without merging**
